project:
  type: website
  output-dir: ../docs/


website:
  title: "Enough R to write a thesis"
  favicon: figures/favicon.png
  repo-url: https://github.com/biostats-r/biostats/biostats-r.github.io
  repo-actions: [edit, issue]
#  sharing: [twitter, facebook]
  twitter-card: true
  navbar: 
    logo: https://biostats.w.uib.no/files/2020/01/biostats-button-res2.png
    logo-alt: BioST@TS homepage
    background: light
    foreground: "#eeaa2c"
    search: true
    rights: 


format:
  html:
    toc: true
    code-tools: 
      source: true
      toggle: false
      caption: none
    highlight-style: a11y
    theme: 
      light: [zephyr, ../css/custom.scss]
      dark: [zephyr, ../css/dark.scss, ../css/custom.scss]
    code-link: true
    number-sections: false
    
execute: 
  echo: false
